import { describe, expect, it } from "vitest";

import { bumpLockVersion, bumpPackageVersion, SyncVersionError } from "./sync-version.mjs";

const TOML = `[package]
name = "confinaid-test-tool"
version = "0.1.0"
edition = "2021"

[lib]
name = "confinaid_test_tool_lib"

[dependencies]
tauri = { version = "2.11", features = ["devtools"] }
version = "9.9.9"
`;

const LOCK = `# This file is automatically @generated by Cargo.

[[package]]
name = "confinaid-test-tool"
version = "0.1.0"
dependencies = [
 "keyring",
 "serde",
]

[[package]]
name = "confinaid-test-tool-helper"
version = "3.3.3"

[[package]]
name = "keyring"
version = "3.7.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;

describe("bumpPackageVersion", () => {
  it("rewrites the [package] version", () => {
    expect(bumpPackageVersion(TOML, "1.2.3")).toContain('version = "1.2.3"\nedition');
  });

  it("does not touch a version outside the [package] table", () => {
    const out = bumpPackageVersion(TOML, "1.2.3");
    // The stray `version = "9.9.9"` under [dependencies] is the exact trap the
    // sibling repo's regex fell into.
    expect(out).toContain('version = "9.9.9"');
    expect(out).toContain('tauri = { version = "2.11"');
  });

  it("is idempotent", () => {
    const once = bumpPackageVersion(TOML, "1.2.3");
    expect(bumpPackageVersion(once, "1.2.3")).toBe(once);
  });

  it("rejects a non-semver version", () => {
    expect(() => bumpPackageVersion(TOML, "not-a-version")).toThrow(SyncVersionError);
    expect(() => bumpPackageVersion(TOML, "1.2")).toThrow(SyncVersionError);
  });

  it("fails loudly when there is no [package] section", () => {
    expect(() => bumpPackageVersion('[dependencies]\nfoo = "1"\n', "1.2.3")).toThrow(
      /no \[package\] section/
    );
  });
});

describe("bumpLockVersion", () => {
  it("rewrites only the entry for the named crate", () => {
    const out = bumpLockVersion(LOCK, "confinaid-test-tool", "1.2.3");
    expect(out).toContain('name = "confinaid-test-tool"\nversion = "1.2.3"');
    // A crate whose name merely starts with ours must be left alone.
    expect(out).toContain('name = "confinaid-test-tool-helper"\nversion = "3.3.3"');
    expect(out).toContain('name = "keyring"\nversion = "3.7.0"');
  });

  it("preserves the rest of the entry verbatim", () => {
    const out = bumpLockVersion(LOCK, "confinaid-test-tool", "1.2.3");
    expect(out).toContain('dependencies = [\n "keyring",\n "serde",\n]');
    expect(out.split("[[package]]").length).toBe(LOCK.split("[[package]]").length);
  });

  it("is idempotent", () => {
    const once = bumpLockVersion(LOCK, "confinaid-test-tool", "1.2.3");
    expect(bumpLockVersion(once, "confinaid-test-tool", "1.2.3")).toBe(once);
  });

  it("fails loudly when the crate is absent", () => {
    expect(() => bumpLockVersion(LOCK, "no-such-crate", "1.2.3")).toThrow(
      /no \[\[package\]\] entry named "no-such-crate"/
    );
  });

  it("handles the last entry in the file, which has no following [[package]]", () => {
    const out = bumpLockVersion(LOCK, "keyring", "9.0.0");
    expect(out).toContain('name = "keyring"\nversion = "9.0.0"');
    expect(out.endsWith("\n")).toBe(true);
  });
});
